# Generated by Django 3.2.5 on 2021-07-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_cmsslider_cms_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_text',
            field=models.CharField(max_length=200, verbose_name='Текст'),
        ),
    ]
